.\" Copyright (c) 1998
.\"	Hans Huebner.  All rights reserved.
.\"
.Dd May 3, 1998
.Dt VCHAT 1
.Os
.Sh NAME
.Nm vchat
.Nd enter the interactive chat system
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm Vchat
is used to participate in chat discussions using a line-mode or full-screen
terminal.
.Sh SEE ALSO
.Xr chatserver 8
.Sh DIAGNOSTICS
.Nm Vchat
is meant to be used by humans, and the messages it produces are meant to
be self-explanatory.  Your mileage may vary.
.Sh ENVIRONMENT
.Nm Vchat
uses the environment variables TERM, CHATSERVER, CHATHELPERL and INPUTRC.